### ISSUE TITLE
Help adapting this for other Focus modes

### ISSUE THREAD

**Issue by olive20xx** [vitorgalvao/calm-notifications-workflow#4]
### Workflow version

2023.5

### Alfred version

5.1.1 [2138]

### macOS version

13.4.1

### Debugger output

```alfred_debugger
This isn't really a bug. I was just wondering if you could help me figure out how to adapt this to other Focus modes besides DND.
```

### More details

I have a focus mode called Coding and I tried to adapt your (very handy workflow, thank you!) to my custom Focus. Right now, it's sorta working. If Coding isn't on, the workflow will turn it on. But when I try to toggle Coding off, it turns on DND. 🫤

I changed everything I can see from Do Not Disturb to Coding.

* Changed DND Keyword to 'coding'
* Changed Identifier from 'dnd' to 'coding'
* Duplicated Calm Notifications shortcut, renamed as Toggle Coding, and changed all "Do Not Disturb"s to "Coding"
* Changed the file to open to "Toggle Coding.shortcut" and replaced Calm Notifications.shortcut with that file in the Workflow folder
* Changed "Select a Shortcut" to "Toggle Coding"

Script Filter:
```
// BUGGED -- toggles DND on when it turns off Coding ;_;
function sfItem(itemObj) {
  return JSON.stringify({
    rerun: 0.5,
    items: [itemObj]
  })
}

function run(argv) {
  // Check if shortcut is installed and grab current Focus
  try {
    const currentFocus = Application("Shortcuts Events")
      .shortcuts
      .byName("Toggle Coding")
      .run({ withInput: "status" })

    // Focus enabled
    if (currentFocus.length > 0) {
      return sfItem({
        title: `Turn off ${currentFocus} Focus`,
        arg: "off"
      })
    }
  } catch {
    return sfItem({
      title: "Missing Toggle Coding Shortcut",
      subtitle: "Press ↩ to install it",
      arg: "install"
    })
  }

  // Focus disabled
  const givenTimeout = argv[0]

  // Any given value must start with a digit
  if (givenTimeout === undefined || !givenTimeout.match(/^\d/)) {
    return sfItem({
      title: "Turn on Coding",
      arg: "on",
      icon: { path: "icon.png" }
    })
  }

  // Calculate timeout
  const timeoutMinutes = givenTimeout.match(/\d\s*h/) ?
    parseInt(parseFloat(givenTimeout) * 60) :
    parseInt(givenTimeout)

  const plurality = timeoutMinutes === 1 ? "minute" : "minutes"

  // Calculate clock
  const date = new Date() // Current time
  date.setMinutes(date.getMinutes() + timeoutMinutes)
  const clock = date.toTimeString().slice(0, 5)

  return sfItem({
    title: `Turn on Coding for ${timeoutMinutes} ${plurality}`,
    subtitle: `Enable until ${clock}`,
    arg: timeoutMinutes,
    icon: { path: "icon.png" }
  })
}
```

Would really appreciate any help you can offer! ❤️

**Comment by vitorgalvao** [comment]
What you need to change from the original is:

* In the Script Filter, change `      .byName("Calm Notifications")` to use the name of your new shortcut.
* In the Run Shortcut, change it to your your new shortcut.
* In your new Shortcut, change the bottom two references of `Do Not Disturb` to `Coding`. *Double check* that it has happened. Shortcuts is incredibly buggy and sometimes you do a change, then go back and it didn’t stick.

That’s all you need for the functionality to be replaced. Everything else are extras.

**Comment by olive20xx** [comment]
Wait, I was wrong. It wasn't actually turning DND on. It was just leaving the general Focus icon in the menu bar. I got confused because the Focus icon is the same as the DND icon. :/

But if I interact with the menu bar icon, it goes away. (Because I have Focus set to "Show When Active" in Control Center Modules.)

Sorry about that! (And yeah, Shortcuts is a pain!)
