### ISSUE TITLE
Stuck on "Getting status"

### ISSUE THREAD

**Issue by Yakitrak** [vitorgalvao/calm-notifications-workflow#7]
### Workflow version

v2023.5

### Alfred version

5.5

### macOS version

14.1.2

### Debugger output

```alfred_debugger
Calm Notifications[Script Filter] Queuing argument ''
```

### More details

When I run `dnd`, it is stuck on `Getting status...`. I have added (and readded twice) the shortcut a few times but still not able to get this workflow to work. Please could you help me in case I have missed something as this should work in my understanding.

<img width="555" alt="image" src="https://github.com/vitorgalvao/calm-notifications-workflow/assets/15147598/9da425bc-0bca-4d48-a246-213cbf5a211e">

**Comment by vitorgalvao** [comment]
Open Script Editor and change the language to JavaScript. Then run the following code. What is the result?

```javascript
Application("Shortcuts Events")
      .shortcuts
      .byName("Calm Notifications")
      .run({ withInput: "status" })
```

**Comment by Yakitrak** [comment]
Do you mean edit the existing script filter for `dnd` and replace with above code?

**Comment by vitorgalvao** [comment]
Sorry, I forgot the link. I mean [the Script Editor app](https://support.apple.com/en-gb/guide/script-editor/scpedt1079/mac).

**Comment by Yakitrak** [comment]
It seems to also be getting stuck 
<img width="759" alt="image" src="https://github.com/vitorgalvao/calm-notifications-workflow/assets/15147598/c9e63f69-4ec9-4d03-9ef0-0705eca54799">

**Comment by vitorgalvao** [comment]
That’s expected, per the reported workflow output. Now try:

```javascript
Application("Safari").activate()
```

If that opens Safari (or brings it to the front if already running), it means something on your Mac is blocking access to Shortcuts (or Shortcuts Events). If that command hangs too, something is stalling AppleScript / `osascript`.

Try rebooting. It it doesn’t work, those keywords might help you find out what the issue is. But the problem is on your Mac, not related to the workflow. If you find the cause and report back, it might help other people in the future.

**Comment by Yakitrak** [comment]
Restarting Mac fixed it, sorry should've tried that first but shortcuts were working for me and other workflows were working so didn't think it was a mac issue. 

For reference to anyone who has this issue, something was going on with Alfred hanging since shortcuts were working and the above code did open Safari. All other workflows were working but one other was also hanging but I had assumed that was a problem with me having incorrect env variables. After restart my mac, this one and the other one are working as expected. Sorry about the inconvenience.

**Comment by vitorgalvao** [comment]
> something was going on with Alfred hanging since shortcuts were working and the above code did open Safari.

That means that what was hanging was Shortcuts Events, because that also stalled in the Script Editor which has no connection to Alfred. If the issue were in the latter, the former would not have hanged.
